# Generated by Django 4.1.3 on 2022-11-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nam', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='pic')),
                ('des', models.TextField()),
            ],
        ),
    ]
